DOCSP-14426 whats new
mongodb/docs-node pull request #169
Opened 2021-04-30 18:42 UTC by kyuan-mongodb

## Pull Request Info

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-14426

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/89cf243/node/docsworker-xlarge/DOCSP-14426-WhatsNew/whats-new/

### Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Does it render on staging correctly?
- [x] Are all the links working?
- [x] Are the staging links in the PR description updated?

2021-04-30 18:58 UTC, terakilobyte requested changes
a few comments/suggestions

2021-04-30 18:58 UTC, terakilobyte commented on source/whats-new.txt
> +New features of the 4.0 Node.js driver release include:
This feels incomplete. Is this meant to target the master branch and 4.0 or just the 3.6 branch?

2021-04-30 18:58 UTC, terakilobyte commented on source/whats-new.txt
> +- Added support for the MONGODB-AWS authentication mechanism using Amazon Web Services (AWS) Identity and Access Management (IAM) credentials
If we have these topics covered in the documentation we should link to them.

2021-04-30 21:41 UTC, terakilobyte approved these changes
lgtm with one correction

2021-04-30 21:41 UTC, terakilobyte commented on source/fundamentals/authentication/mechanisms.txt
> +.. _mongosb-aws:
```suggestion
.. _mongodb-aws: 
```

2021-04-30 21:42 UTC, terakilobyte commented on source/whats-new.txt
> +- Added support for the :ref:`MONGODB-AWS <mongosb-aws>` authentication mechanism using Amazon Web Services (AWS) Identity and Access Management (IAM) credentials
```suggestion
- Added support for the :ref:`MONGODB-AWS <mongodb-aws>` authentication mechanism using Amazon Web Services (AWS) Identity and Access Management (IAM) credentials
```

2021-05-03 14:40 UTC, kyuan-mongodb commented
Hi @emadum, This PR is ready for review

2021-05-04 12:45 UTC, emadum requested changes
Found a typo but otherwise LGTM 👍

2021-05-04 12:45 UTC, emadum commented on source/whats-new.txt
> +- The :ref:`update() <updateDocuments>` and :ref:`reaplceOne() <replacementDocument>` methods support index hints
```suggestion
- The :ref:`update() <updateDocuments>` and :ref:`replaceOne() <replacementDocument>` methods support index hints
```

2021-05-06 16:39 UTC, emadum approved these changes

2021-05-06 16:47 UTC, merged