DOCSP-19604: mongoclient srv options (WIP)
mongodb/docs-node pull request #268
Opened 2021-11-10 18:27 UTC by ccho-mongodb

## Pull Request Info

Waiting on response as to whether the srvServiceName setting overrides the protocol specified in the connection string.

### Issue JIRA link:
https://jira.mongodb.org/browse/DOCSP-19604

### Snooty build log:
[**Paste your workerpool job link here**](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?jobId=618c0ca8c13055282dd0dfaf)

### Docs staging link (requires sign-in on MongoDB Corp SSO):
https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-19604-srv-options/fundamentals/connection/#connection-options

### Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Does it render on staging correctly?
- [ ] Are all the links working?
- [ ] Are the staging and workerpool job links in the PR description updated?

### If your page documents a concept, does it meet the following criteria?

- [ ] Target the [Jasmin persona](https://drive.google.com/file/d/14FbBOLCVxwSP6M9BK4Nz1Ir9tzxT8_02/view)
- [ ] Target the [Lucas persona](https://drive.google.com/file/d/1J2vqJxo7ldv7OP_obA9Q-avf0o_ju4Lk/view)

2021-11-10 20:13 UTC, terakilobyte approved these changes
copy lgtm

2021-11-11 15:11 UTC, nbbeeken approved these changes

2021-11-11 15:12 UTC, dariakp requested changes

2021-11-11 15:12 UTC, dariakp commented on source/fundamentals/connection.txt
> +   * - **srvMaxHosts**
let's clarify that `0` means "unlimited"

2021-11-11 16:33 UTC, dariakp requested changes

2021-11-11 16:33 UTC, dariakp commented on source/fundamentals/connection.txt
> +         not using the SRV connection protocol
Just a tiny nit for consistency:
```suggestion
         not using the SRV connection protocol.
```

2021-11-16 22:41 UTC, dariakp approved these changes

2021-11-16 22:42 UTC, dariakp commented
We merged the implementation and planning to release tomorrow, so this PR should be all clear to go in, thanks! @terakilobyte

2021-11-17 16:52 UTC, merged