DOCSP-31324: keepalive settings removed + defaults
mongodb/docs-node pull request #738
Opened 2023-08-10 19:14 UTC by rustagir

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-node/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-31324>
**Staging**
- [faq entries](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31324-tcp-keepalive-defaults/faq/#what-does-the-keepalive-option-do-)
- [what's new](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31324-tcp-keepalive-defaults/whats-new/#what-s-new-in-6.0)
- [upgrade guide](https://docs-mongodbcom-staging.corp.mongodb.com/node/docsworker-xlarge/DOCSP-31324-tcp-keepalive-defaults/upgrade/#version-6.x-breaking-changes)

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Did you run a spell-check?
- [x] Did you run a grammar-check?
- [x] Are all the links working?

2023-08-10 21:00 UTC, mongoKart requested changes
Not any major blockers, but I'd appreciate another look

2023-08-10 21:00 UTC, mongoKart commented on source/upgrade.txt
> +  options. Internally, the value of ``keepAlive`` is set to ``true`` and the
Also applies below

2023-08-22 19:11 UTC, rustagir commented on source/faq.txt
> +that it exhibits the following behavior:
changed and changed the bullet point text to match

2023-08-23 21:00 UTC, mongoKart approved these changes
LGTM!

2023-08-23 21:11 UTC, merged