DOCSP-34101-create-bulk-operations-page
mongodb/docs-node pull request #948
Opened 2024-12-11 19:19 UTC by gmiller-mdb

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-node/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-34101>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2025-01-03 18:31 UTC, stephmarie17 requested changes
Nice work ✨ a few formatting updates and style guide suggestions in the comments.

2025-01-03 18:31 UTC, stephmarie17 commented on source/fundamentals/crud/write-operations/bulk.txt
> +- `BulkWrite() </https://mongodb.github.io/node-mongodb-native/6.12/classes/Collection.html#bulkWrite>`__
[s] In the `snooty.toml` file you can find the variable to shorten these URLS, it's `{+api+}` + rest of the URL. Can help avoid small typos with these long links:
```suggestion
- `BulkWrite() <https://mongodb.github.io/node-mongodb-native/6.12/classes/Collection.html#bulkWrite>`__
```

2025-01-03 18:31 UTC, stephmarie17 commented on source/fundamentals/crud/write-operations/bulk.txt
> +- `BulkWrite() </https://mongodb.github.io/node-mongodb-native/6.12/classes/Collection.html#bulkWrite>`__
With the variable: 
```suggestion
- `BulkWrite() <{+api+}/classes/Collection.html#bulkWrite>`__
```

2025-01-06 17:44 UTC, stephmarie17 approved these changes
LGTM with a small comment!

2025-01-06 17:44 UTC, stephmarie17 commented on source/code-snippets/crud/bulk.js
> +            {title: "Inception", year: 2010, rated: "PG-13", released: "2010-07-16"},
[s] I don't think these spacings needed to removed, sorry if my last comment was confusing! I meant the indentation spacing:
```suggestion
          { title: "Inception", year: 2010, rated: "PG-13", released: "2010-07-16" },
```

2025-01-06 21:11 UTC, W-A-James requested changes

2025-01-06 21:11 UTC, W-A-James commented on source/fundamentals/crud/write-operations/bulk.txt
> +.. _node-bulk-operation-types:
Either in this section or in each of the operation type examples, we should show the assignment of the `movies` variable in the example code to clarify to users that `movies` is a `Collection` object.

2025-01-06 22:15 UTC, W-A-James approved these changes
LGTM 👍🏿

2025-01-07 18:17 UTC, merged