DOCSP-4466 Add CSOT
mongodb/docs-node pull request #951
Opened 2024-12-13 23:59 UTC by stephmarie17

# Pull Request Info

[PR Reviewing Guidelines](https://github.com/mongodb/docs-node/blob/master/REVIEWING.md)

JIRA - <https://jira.mongodb.org/browse/DOCSP-44666>
Staging - <https://docs-mongodbcom-staging.corp.mongodb.com/drivers/docsworker-xlarge/NNNNN/>

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Did you run a spell-check?
- [ ] Did you run a grammar-check?
- [ ] Are all the links working?
- [ ] Are the [facets and meta keywords](https://wiki.corp.mongodb.com/display/DE/Docs+Taxonomy) accurate?

2024-12-20 20:11 UTC, lindseymoore requested changes
Overall good, thanks for taking this! Some suggestions for clarity and small fixes. I'll be back Jan 7, but Mike says he is available for re-review if you want it back a little sooner. Have a great holiday break!

2025-01-02 19:53 UTC, mongoKart requested changes
lots of comments, but they're all small. great work!

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +specify a **client-side operation timeout**. The timeout applies to all steps
```suggestion
specify a **client-side operation timeout (CSOT)**. The timeout applies to all steps
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +You can specify a timeout by using the ``timeoutMS`` option.
S: remove from here and mention only under the first heading

```suggestion
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +   The Client-Side Operation Timeout (CSOT) feature is experimental and might
```suggestion
   The CSOT feature is experimental and might
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +``timeoutMS`` connection option to the timeout length in milliseconds.
S: make this the opening paragraph, then add the previous paragraph to the end of it

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +   options.
S: combine into single note

```suggestion
.. note:: 

   The ``timeoutMS`` connection option takes precedence over the
   following options:

   - ``socketTimeoutMS``
   - ``waitQueueTimeoutMS``
   - ``wTimeoutMS``
   - ``maxTimeMS``
   - ``maxCommitTimeMS``

   When the CSOT feature is no longer experimental, the preceding options will
   be deprecated.
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +specified timeout to each server operation. The following code example specifies
q: i thought the timeout applied to the total time for all operations in the aggregate. does this depend on the level at which you specify it?

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +   const uri = "mongodb://<db_username>:<db_password>@<hostname:<port>";
S: remove authentication details since there are several kinds they could be using

```suggestion
   const uri = "mongodb://<hostname:<port>";
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +~~~~~~~~~~~~~~~~~~~~
s: could be confused with JS object inheritance

```suggestion
Timeout Inheritance
~~~~~~~~~~~~~~~~~~~
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +- **Operation Level**: Takes the highest precedence and will override ``timeoutMS``
if this order is hierarchical, it might make more sense as a numbered list to clearly show precedence.

it could also be helpful to word every list entry in the same way. e.g.: 'Applies to X. Can be overridden by Y.' you could also structure it as a table if you like the look of it.

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +- **Collection Level**: Inherits to all sessions and operations on that
should this be 'applies to'?

```suggestion
- **Session Level**: Applies to all transactions and operations within
  that session, unless the option is overridden by options set at those levels.

- **Collection Level**: Applies to all sessions and operations on that
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +The Node.js driver supports various levels of configuration to control the
```suggestion
The {+driver-short+} supports various levels of configuration to control the
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +Transactions
q: can you help me understand the relationship between Overrides / Transactions / Client Encryption? it almost seems like overrides should be appended to the previous section on inheritance.

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +iteration mode.
```suggestion
Cursors require special handling when you use the CSOT feature. 
You can configure
cursors to interact with CSOT by using either the cursor lifetime or cursor
iteration mode.
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +The ``cursorLifetime`` mode uses ``timeoutMS`` to bound the entire lifetime of a
s:

```suggestion
The ``cursorLifetime`` mode uses ``timeoutMS`` to limit the entire lifetime of a
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +``find()``, ``aggregate()``, or ``listCollections()``. In this mode, the initialization
```suggestion
those returned by the ``find()``, ``aggregate()``, and ``listCollections()`` methods.
In this mode, the initialization
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +of the cursor and all subsequent ``getMore()`` calls must finish within the limit
s:

```suggestion
of the cursor and all subsequent calls to the ``getMore()`` method must finish within the limit
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +specified with ``timeoutMS``. If they do not, the system throws a timeout error.
```suggestion
specified by the ``timeoutMS`` option. If they do not, the system throws a timeout error. 
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +``close()`` method, resets the timeout.
s:

```suggestion
When you close a cursor by calling the ``toArray()`` or ``close()`` method,
the timeout resets.
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +of all documents occur within 10 seconds, as shown in the following example:
s: this reads like a direction, which i don't think it is

```suggestion
The following example shows how to set the ``timeoutMS`` option to ensure that
the cursor is initialized and all documents are retrieved within 10 seconds:
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +The ``cursorLifetime`` mode uses ``timeoutMS`` to bound the entire lifetime of a
i don't see this term used in code, so i'd use normal formatting

```suggestion
The cursor lifetime mode uses ``timeoutMS`` to bound the entire lifetime of a
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +The iteration mode uses ``timeoutMS`` to bind each ``next()``, ``hasNext()``, or
s:

```suggestion
The cursor iteration mode uses the ``timeoutMS`` option to limit each ``next()``, ``hasNext()``, or
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +``tryNext()`` call. The timeout refreshes after each call completes. This is the
```suggestion
The iteration mode uses ``timeoutMS`` to bind each call to the ``next()``, ``hasNext()``, or
``tryNext()`` method. The timeout refreshes after each call completes. This is the
```

2025-01-02 19:53 UTC, mongoKart commented on source/fundamentals/connection/csot.txt
> +capped collections or change streams.
```suggestion
default mode for all tailable cursors, such as the tailable cursors returned by
the ``find()`` method on capped collections or change streams.
```

2025-01-03 19:51 UTC, stephmarie17 commented on source/fundamentals/connection/csot.txt
> +specified timeout to each server operation. The following code example specifies
It's been awhile since I initially wrote this but if I recall correctly this was how CSOT is also described in the PyMongo doc so I carried this intro over but will see if there is a better way to describe this during technical review!

2025-01-03 21:43 UTC, stephmarie17 commented on source/fundamentals/connection/csot.txt
> +Transactions
Yeah I was debating how to organize this and actually ended up adding the inheritance section after writing these for additional clarity around the expected behavior. I added that as a subsection thinking it was more connected to the option, while the Overrides section calls out some behavior specific to the example use case, transactions, and client encryption. Mostly based on what was requested in the ticket. Does this make sense as is or do you think it needs further tweaking on the section headings?

2025-01-03 22:59 UTC, stephmarie17 commented on source/fundamentals/connection/csot.txt
> +- **Operation Level**: Takes the highest precedence and will override ``timeoutMS``
I updated it to be a table I kind of think that makes it easier to skim lmk what you think!

2025-01-08 18:15 UTC, lindseymoore approved these changes
Small comments and fix, great work on this! LGTM :)

2025-01-14 19:37 UTC, nbbeeken requested changes

2025-01-14 19:37 UTC, nbbeeken commented on source/fundamentals/connection/csot.txt
> +seconds to retrieve documents:
```suggestion
as they are added to a collection and times out if it takes longer than 10
seconds to retrieve a document:
```

Practically speaking, the timeout is only going to be "counted down" when fetching a batch of documents, so this is accurate. However, the intention is that from the user's perspective, each next call (so per document) is bounded by the timeoutMS value.

2025-01-14 19:37 UTC, nbbeeken commented on source/fundamentals/connection/csot.txt
> +   };
While tailable cursors are defaulted to the other timeoutMode I think that their usage is rare enough that it is unnecessary for us to combine their use with the timeoutMode setting for our only example for iteration mode. 

If I am using a normal find cursor and I want to perform some async action for each document timeoutMode=iteration is what I'm going to want to use so I don't bound my "some action" code by the driver's timeoutMS setting:

```ts
for await (const movie of mflix.find({}, { timeoutMode: 'iteration' })) {
  const imdbResponse = await fetch(movie.imdb_url);
  console.log(await imdbResponse.text());
}
```

If you left the timeoutMode in lifetime here then the cursor's time to finish would likely be deeply cut into by the http fetch operation. I think an example like this is a bit more practical to the average user compared to tailable cursors.

2025-01-14 19:37 UTC, nbbeeken commented on source/code-snippets/connection/csot.js
> +const { MongoClient } = require('mongodb');
```suggestion
import { MongoClient } from "mongodb";
```

2025-01-15 20:31 UTC, stephmarie17 commented on source/fundamentals/connection/csot.txt
> +the database, collection, session, transaction, or operation levels.
Will update and add an example 👍

2025-01-15 20:32 UTC, stephmarie17 commented on source/fundamentals/connection/csot.txt
> +10 seconds when instantiating a new ``MongoClient`` instance:
If it is more expected as a use case, I think using 30 seconds as the example here makes sense. Will update.

2025-01-15 20:36 UTC, stephmarie17 commented on source/fundamentals/connection/csot.txt
> +
Adding, let me know if the update is accurate!

2025-01-15 20:38 UTC, stephmarie17 commented on source/fundamentals/connection/csot.txt
> +Cursors require special handling when you use the CSOT feature. You can configure
Revising!

2025-01-15 20:47 UTC, stephmarie17 commented on source/fundamentals/connection/csot.txt
> +``getMore()`` method must finish within the limit specified by the ``timeoutMS``
Rephrasing a bit, lmk if the update looks good.

2025-01-15 21:14 UTC, stephmarie17 commented on source/fundamentals/connection/csot.txt
> +timeout resets.
You can ignore the failing test, our linter gets mad at the word `killCursors` 😅

2025-01-15 21:16 UTC, stephmarie17 commented on source/fundamentals/connection/csot.txt
> +10 seconds when instantiating a new ``MongoClient`` instance:
Note: I didn't update all of the examples to have a longer timeout but lmk if you think that is preferrable!

2025-01-15 21:34 UTC, nbbeeken approved these changes
LGTM

looks like there's a linter error of sorts. Unfortunately, killCursors is the name of the command so that can't be rephrased 😅

2025-01-15 22:07 UTC, merged